version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
